const lessons=[
{id:'basic',title:'شناخت همستر و رفتارها',cat:'مبانی نگهداری',level:'مبتدی',time:'۸ دقیقه',progress:72,img:'assets/images/course-basic.svg',desc:'زبان بدن، خواب، فعالیت شبانه و رفتارهای رایج همستر.'},
{id:'home',title:'ساخت خانه امن و استاندارد',cat:'محیط زندگی',level:'مبتدی',time:'۱۲ دقیقه',progress:45,img:'assets/images/course-home.svg',desc:'انتخاب قفس، بستر، چرخ، تونل و نقاط مخفی برای کاهش استرس.'},
{id:'health',title:'تغذیه، سلامت و علائم خطر',cat:'سلامت',level:'متوسط',time:'۱۵ دقیقه',progress:25,img:'assets/images/course-health.svg',desc:'غذای مناسب، خوراکی‌های ممنوع و نشانه‌هایی که باید جدی بگیرید.'},
{id:'play',title:'بازی، تمرین و اجتماعی‌سازی',cat:'رفتار و تمرین',level:'متوسط',time:'۱۰ دقیقه',progress:64,img:'assets/images/course-play.svg',desc:'روش‌های آرام برای عادت دادن همستر به دست و محیط.'}
];
const nav={home:'index.html',categories:'pages/categories.html',lesson:'pages/lesson.html',quiz:'pages/quiz.html',profile:'pages/profile.html',favorites:'pages/favorites.html',settings:'pages/settings.html',about:'pages/about.html'};
function basePath(){return location.pathname.includes('/pages/')?'../':''}
function initTheme(){const t=localStorage.getItem('ha-theme')||'light';document.documentElement.dataset.theme=t;document.querySelectorAll('[data-theme-toggle]').forEach(b=>b.onclick=()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('ha-theme',n)})}
function shell(active='home'){const b=basePath();document.body.insertAdjacentHTML('afterbegin',`<header class="topbar"><div class="container nav"><a class="brand" href="${b}index.html"><span class="brand-mark"><img src="${b}assets/icons/hamster.svg" alt=""></span><span>آکادمی همستر</span></a><nav class="nav-links"><a class="${active==='home'?'active':''}" href="${b}index.html">خانه</a><a class="${active==='categories'?'active':''}" href="${b}pages/categories.html">آموزش‌ها</a><a class="${active==='quiz'?'active':''}" href="${b}pages/quiz.html">آزمون</a><a class="${active==='favorites'?'active':''}" href="${b}pages/favorites.html">علاقه‌مندی‌ها</a><a class="${active==='about'?'active':''}" href="${b}pages/about.html">درباره ما</a></nav><button class="icon-btn" data-theme-toggle title="تغییر تم">◐</button></div></header>`);document.body.insertAdjacentHTML('beforeend',`<nav class="bottom-nav"><a class="${active==='home'?'active':''}" href="${b}index.html">🏠<span>خانه</span></a><a class="${active==='categories'?'active':''}" href="${b}pages/categories.html">📚<span>آموزش</span></a><a class="${active==='quiz'?'active':''}" href="${b}pages/quiz.html">🧠<span>آزمون</span></a><a class="${active==='favorites'?'active':''}" href="${b}pages/favorites.html">⭐<span>ذخیره</span></a><a class="${active==='profile'?'active':''}" href="${b}pages/profile.html">👤<span>پروفایل</span></a></nav>`);initTheme()}
function card(l){const b=basePath();const img=l.img.startsWith('assets')?b+l.img:l.img;return `<article class="card course-card fade-in"><a href="${b}pages/lesson.html?id=${l.id}"><div class="course-cover"><img src="${img}" alt="${l.title}"></div><div class="course-body"><div class="meta"><span class="pill">${l.cat}</span><span class="pill">${l.level}</span><span class="pill">${l.time}</span></div><h3>${l.title}</h3><p>${l.desc}</p><div class="progress"><span style="width:${l.progress}%"></span></div></div></a><div style="padding:0 18px 18px"><button class="btn btn-soft" onclick="toggleFav('${l.id}')">⭐ ذخیره آموزش</button></div></article>`}
function renderCourses(elId,items=lessons){const el=document.getElementById(elId);if(el)el.innerHTML=items.map(card).join('')}
function favs(){return JSON.parse(localStorage.getItem('ha-favs')||'[]')}function toggleFav(id){let f=favs();f=f.includes(id)?f.filter(x=>x!==id):[...f,id];localStorage.setItem('ha-favs',JSON.stringify(f));alert(f.includes(id)?'به علاقه‌مندی‌ها اضافه شد':'از علاقه‌مندی‌ها حذف شد')}
function renderLesson(){const id=new URLSearchParams(location.search).get('id')||'basic';const l=lessons.find(x=>x.id===id)||lessons[0];document.title=l.title;document.getElementById('lessonTitle').textContent=l.title;document.getElementById('lessonMeta').textContent=`${l.cat} • ${l.level} • ${l.time}`;document.getElementById('lessonBody').innerHTML=`<p>${l.desc}</p><div class="lesson-step"><h3>۱. مشاهده آرام و بدون عجله</h3><p>همسترها معمولاً شب‌فعال هستند. در ساعات استراحت آن‌ها مزاحم نشوید و رفتارهای تکراری، پنهان شدن یا جویدن زیاد را با تغییر محیط بررسی کنید.</p></div><div class="lesson-step"><h3>۲. محیط امن</h3><p>بستر عمیق، چرخ استاندارد، خانه مخفی، آب تازه و مسیرهای کاوش باعث کاهش استرس می‌شود.</p></div><div class="lesson-step"><h3>۳. تمرین روزانه کوتاه</h3><p>جلسه‌های ۵ تا ۱۰ دقیقه‌ای، با تشویقی کوچک و حرکت آرام دست، اعتمادسازی را بهتر از تمرین‌های طولانی انجام می‌دهد.</p></div>`}
function initQuiz(){const qs=[{q:'همسترها معمولاً چه زمانی فعال‌تر هستند؟',a:['صبح زود','شب و غروب','ظهر'],c:1},{q:'برای کاهش استرس چه چیزی ضروری است؟',a:['صدای بلند','خانه مخفی و بستر مناسب','نور مستقیم'],c:1},{q:'تمرین اعتمادسازی بهتر است چگونه باشد؟',a:['کوتاه و آرام','طولانی و اجباری','بدون تشویقی'],c:0}];let score=0,idx=0;const box=document.getElementById('quizBox');function draw(){const x=qs[idx];box.innerHTML=`<h2>${x.q}</h2>${x.a.map((o,i)=>`<button class="quiz-option" data-i="${i}">${o}</button>`).join('')}<p class="lead">سؤال ${idx+1} از ${qs.length}</p>`;box.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{const ok=+btn.dataset.i===x.c;btn.classList.add(ok?'correct':'wrong');if(ok)score++;setTimeout(()=>{idx++;idx<qs.length?draw():box.innerHTML=`<h2>نتیجه آزمون</h2><p>امتیاز شما: ${score} از ${qs.length}</p><button class="btn btn-primary" onclick="location.reload()">تکرار آزمون</button>`},650)})}draw()}
function saveProfile(){const n=document.getElementById('nameInput')?.value||'دوست همسترها';localStorage.setItem('ha-name',n);document.getElementById('profileName').textContent=n}
function initProfile(){const n=localStorage.getItem('ha-name')||'دوست همسترها';document.getElementById('profileName').textContent=n;document.getElementById('nameInput').value=n}
document.addEventListener('DOMContentLoaded',()=>document.body.classList.add('ready'));
